language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - gongguochuanqi@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: t3ko6Cu3IUvFd9msQsc07xbRpPVm9kmRlj8BMgDRMdJo0D5RcnhWMY7rcbZ0Y1wMlcPbhm53+e0fF/nLg3eKQXvWvsgEcS86Cx+izebKb8Z8LOr3nrayRBiBTcvIkCiBz6DcVEJjITiC+2f8cI85FHeVUzcALVVhdp3yhGYLJAUGosf+g6LuVWc/npamEvIXJt1aHHhhiG9YbGEb8Fd0IKq54wEq+azEZ/GoSdPYOesgU2cyKaMEcLj32vUh7Th2eY4y/l6Yc0BEHEXqBoJAWYf0rtlGpsk3Z2Hznu0+4cCrJKJxoocZlp0TCNXF7+Sa/0VmZECDYkm/Ltdn7Ea+VOkUx3AhQZtmjN4mXowBUzAD7+ZqY97Y+xbpaRfimZtYyjs13kxPr/Q/svSoqNigxxAHEwWY1HbFY2CF81tTvtQr9ZmdzrJEVLA9QoqXhMLcO23fBuTYqVNFdAASYWeHlCldKYVR6GLTU4saheb2yTSoeZLE5i2wYG+cHXz0Ozz446NEICfMPSE12vewePHVvU1nJe9vurK5XmcwzwcHQG0G5GjJxKhZd1X8DiCF+9J5SsaRQF4jPiiOGLxcV1bDXE6GGK/yTLNSHYtUjrHaEEVH4URfOT7u+wx8RlREiOn7eIlaL1dyoJ1WptURJVjrwNLCn4caVgBUehF3KQDexig=
  - secure: xgm23tazs4YpUjnYUbI/1vuLomGxvYanoa1cKbsTM6sCJuouOY5ME9wFIda5E1PzkA8PwDlrEjKRw7iEHyhZn8axCOS56j4UafnjW8w29MDeL1djPDVgATqwGjE6nWpwkKpq3RT5N0PESvUT4CMnI7wyK4WsuypIG2/f/7rDJnoyFU+EHdnL+5drl6JPgSIVq834Jt8pBObMUWFWWp1sZQbgh72gOUIyazQMJVLs3w1iYJ+4jxyybQVrid9MjljVuRwdBEjVUJivm8WQGWqgGxqeOzdsLo0hdzwadTsvJ0hs/sRGSXDmT6BIENtW2JL1oQxIW1UzkeyK/7tP2I25qKDxb31VhdCrdjm9FtO+/V3+E8Gn55seLL8XKc5tVC96e+v7zNlbisl0VDk1HTI2Q991Tz2DkbwMqONiXFWmGnXMh3l8jJXfUP8dL8V8OOd8ReOl8iC3mwHmrpYsFSq4+96g7jHZrh68Fim/6jmqEI6SmTsq77zOOG9ftUpJ/4Sk6MQEN9PG524aaDuNq/j2isCYIBfEQcDUWJ8paK2l4K2WV6l552JU6hKwJqtya12s4HsnNuG+E94h0HMvWqJmk1M9YiRCxIPttHxna64Iyrr6YKQkWoSLZ23jjPVAnErhkauBi8c4xl0wng3dXoV1ii6U5RhkbKFZWqXtttRIrkI=
  - secure: b2DRYIovBZymRklsk7UbuyEsejaaFU0LzcNy1oLbvvAw5mClyUuC/F9V0Bl+4U4JzBZ0QsZ75Veh7awprY7DbIFrqtFEBHs5zorZ2RAkusbVYocek+ejQaDoFRDxsEtfa2HH/8rb3m72iaYbUPqSqiKze2UL2g2q/BKdgsWYsI175TDwMAsIPQf0gttWhCDm2KI2XAN0IpTwij2sb9hkTepyvvST7D7wU/7vOsYyVcWZRSEtbHqsM6dJ/VEm2dWO+O9evDXK5tuAUCWhl9VTx3nxUz0EU4X7ZP7m4KfkaoBotrDOPGWBYZ2cNwbTIuuq68fC080sto/Jae1E5gbIOyTbJrseLKnz5+ZUOLW4YEpqUzFAwRThH+kKtFRe+tmazfu5zOUvcwkcoE5rmXPLoyWIh4jIMicWu/08bTLvhgtZt0hnGmW4nltiSikvYRD9kyLU0ZMCcOX7y6h5VmPlC4BcgUh2SqCgX6nPsBE0KvBW7obMR0dKctDB2QdwHMKAOLn8h+ojm06HmgSxbhOtzUrMNYatVnqeCFXReHUyEG/g9bLU8/1tUoJGCKLLbIp6JwZ+zW0Pu/RXZkVVeuojO7EVreqi8LjfHToQMnzVxvN2rOnS6OThJgIHxhcmHNbOpS2M7SeMcij+SQrgs0m72Ey+dXMWzLFmCSmkbztnnbw=
  - secure: Wuzz6nl1BR0T4A9xpBw9nTTljm52ajiHJxTyHQ70LspoMWi1GJRaghpfS6Z32Of2QmiLR1AG8mMLqORPnCnxTqJj9S53bjO0B8u2jQxk4UQFCQ4k0J/rpMdAR4eAU3yAxXpnNMYrhOduss04kyh9JsNtz49qZreSJYFwpvtQX3bQbuczGqXjFpjf9vTe0+cvV8hlPvO1gxykCd23H4FiC3UonYZqysdc8Hrbljix6E7RUB3tfDYjql5PQDt4BAYOJj/xo5/Y4U/SFnDpWs8Gme+bAOun/+UgaP1dGhJ3Rc8pe8wvOtgVofmAyhk9142cZrOtjpZMHljbg+TVVBbUWHOnxjKCFdofUo0zZeBniofajPmN1YipXrNjWuHMkN+Pp6wQYMyQcDAGD0sGXxucBLuyioVqS5148jWjnbUBYSVECprKh30ArZ/oAEGh6O3/2ZdI/iMfw3+44BKtN/0NPwgnfW3CJPTZavSnlshtv1IAT9Beq0jmElOh2d5v55t249js52uaBcHaPrKUVpuQfGRrV6t56ESL7k5Xuo7H3t0CdwocVZ5uujHOEnABcvumDDJdUx/wDMhIPTUTlxkE8LcpoBpWsezRbbI9S3aqszXXjdOjteFLWUT0YfFnZGDZTh5V0qto5dSLZ2kbRW4NIj1MuKmCXJwEbW9ZsR9ICHw=
  - secure: JBqrEXBg+zmD//4NsXlF9InnI7yzQfrKssnj+/9Fugf7Bf7wDiFv90zbaigpVZM9FCcm8T6kXHlYa7261aShhMZl8idRIOUIqQZwrK9NY2uVCGQhAlbdc0tmZkRZG/foR4rM2FZNlWc3fes3QuIKEo54mGsA0oE+X0Cp6xTBvz+EWUYsRl4cgsGQAfe3YBxwsRtgTCEdTIZcMHdzwPcpWp9LRxrhKWJE7pJV5c6JgCQTQFjoTk6PrPcUTsiBxOR17o9O6TDWALSOmpJkVy6EvfTcPw+S6s4TVrmiZ9LtG+5Ss6ECniZP5zAaxMwLp3tGDFO13T1M6RhDK3QBZNaR1VvIIWHap6IuTd4bYhAIQvVIMA6ms8rUx3cBss4pCkOpGNYtaiEBiQf33jUfq9kBSpGoSdQJmvH9zTMufeg6X2aqhkozDTr73mXbDu31Gt1aoZDkZt4a3Ccfo/+c43GbMYAm0GsHL5O3V1bfr982Fs7XplF1TzEI7Ra5r/kDBwtl+ynHl3vcgSO4dpIuAjAe5vuSI7HQBki1r22oErOMsFtOLVxQxPpfPBadM7VITHlJByGNKO+NweTyKU8+NCto3yWR3mZxDu3ammuRYHHu58xHPLW3XfDPLf4qijXxjHnmEQ+TlBrPn/of7dPQlpJfRTzjYi7jnWdEBzoqUM/z7IM=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=unique-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
