version: '2'
services:
  eurekaserver:
     image:   johncarnell/tmx-eurekasvr:unique
     ports:
       - "8761:8761"
  configserver:
      image: johncarnell/tmx-confsvr:unique
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY:       "IMSYMMETRIC"
  # configserver2:
  #     image: johncarnell/tmx-confsvr:unique
  #     ports:
  #        - "8889:8889"
  #     links:
  #         - "eurekaserver:eurekaserver"
  #     environment:
  #       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  #       EUREKASERVER_PORT:8761
  #       ENCRYPT_KEY:       "IMSYMMETRIC"
#  zuulserver:
#      image: johncarnell/tmx-zuulsvr:unique
#      ports:
#        - "5555:5555"
#      environment:
#        PROFILE: "default"
#        SERVER_PORT: "5555"
#        IP_ADDRESS: "10.254.173.251"
#        CONFIGSERVER_URI: "http://configserver:8888"
#        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#        EUREKASERVER_PORT:        "8761"
#        DATABASESERVER_PORT:      "5432"
#        CONFIGSERVER_PORT:        "8888"
#        ORGSERVERNEW_PORT:        "8087"
#        ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
      image: postgres:9.5
      ports:
      - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=p0stgr@s
        - POSTGRES_DB=eagle_eye_local
  licensingservice:
      image: johncarnell/tmx-licensing-service:unique
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        IP_ADDRESS: "10.254.173.251"
#        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
      image: johncarnell/tmx-organization-service:unique
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        IP_ADDRESS: "10.254.173.251"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice2:
      image: johncarnell/tmx-organization-service:unique
      ports:
        - "8086:8086"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8086"
        IP_ADDRESS: "10.254.173.251"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  orgservice-new:
      image: johncarnell/tmx-orgservice-new:unique
      ports:
        - "8087:8087"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8087"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:        "8761"
        DATABASESERVER_PORT:      "5432"
        CONFIGSERVER_PORT:        "8888"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  specialroutes-service:
      image: johncarnell/tmx-specialroutes-service:unique
      ports:
        - "8910:8910"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8910"
        IP_ADDRESS: "10.254.173.251"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:        "8761"
        DATABASESERVER_PORT:      "5432"
        CONFIGSERVER_PORT:        "8888"
        ENCRYPT_KEY:       "IMSYMMETRIC"
