## +++ for local test.
#database:
#    image: postgres:9.5
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=p0stgr@s
#      - POSTGRES_DB=eagle_eye_local
#
#redis:
#    image: redis:alpine
#    ports:
#      - 6379:6379
## --- for local test.

kafkaserver:
    image: spotify/kafka
    mem_limit: 805306368
    ports:
      - "2181:2181"
      - "9092:9092"

zipkin:
    image: atzu68/tmx-zipkinsvr:${BUILD_NAME}
    mem_limit: 805306368
    ports:
      - "9411:9411"
    environment:
      PROFILE: "default"
      SERVER_PORT: "9411"

logspout:
    image: gliderlabs/logspout
    command: syslog://logs6.papertrailapp.com:19615
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

eurekaserver:
   image:   atzu68/tmx-eurekasvr:${BUILD_NAME}
   mem_limit: 805306368
   ports:
       - "8761:8761"

configserver:
    image: atzu68/tmx-confsvr:${BUILD_NAME}
    #mem_limit: 1073741824
    mem_limit: 805306368
    ports:
       - "8888:8888"
    links:
       - "eurekaserver:eurekaserver"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       ENCRYPT_KEY:       "IMSYMMETRIC"

zuulserver:
    image: atzu68/tmx-zuulsvr:${BUILD_NAME}
    mem_limit: 805306368
    ports:
      - "5555:5555"
    links:
      - "eurekaserver:eurekaserver"
      - "configserver:configserver"
      - "zipkin:zipkin"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ZIPKIN_URI: "http://zipkin:9411"

authenticationservice:
    image: atzu68/tmx-authentication-service:${BUILD_NAME}
    mem_limit: 805306368
    ports:
      - "8901:8901"
    links:
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
#      - "database:database" # TODO
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8901"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"

licensingservice:
    image: atzu68/tmx-licensing-service:${BUILD_NAME}
    mem_limit: 805306368
    ports:
      - "8080:8080"
    links:
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
      - "kafkaserver:kafkaserver"
      - "authenticationservice:authenticationservice"
      - "zipkin:zipkin"
#      - "database:database" # TODO
#      - "redis:redis" # TODO
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      AUTHSERVER_URI:   "http://authenticationservice:8901/user"
      ZIPKIN_URI: "http://zipkin:9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"

organizationservice:
    image: atzu68/tmx-organization-service:${BUILD_NAME}
    mem_limit: 805306368
    ports:
      - "8085:8085"
    links:
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
      - "kafkaserver:kafkaserver"
      - "authenticationservice:authenticationservice"
      - "zipkin:zipkin"
#      - "database:database" # TODO
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      AUTHSERVER_URI:   "http://authenticationservice:8901/user"
      ZIPKIN_URI: "http://zipkin:9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
